### ISSUE TITLE
pdf-opener.sh

### ISSUE THREAD

**Issue by jcguu95** [jamesbvaughan/dotfiles#1]
Hi James,

I read your article about qutebrowser in your blog, and am interested in your pdf-opener script. I am pretty new here and not familiar with programming language. May I ask how you integrate "pdf-opener.sh" in your workflow? Is it also possible to integrate that shell script with qutebrowser? Thank you, and my apologize if the question is too naive.

**Comment by jamesbvaughan** [comment]
Hi @jcguu95, I'm glad you found this interesting! No need to apologize, that's a totally valid question.

I integrate it into my workflow by binding it to `Super + f`, so a common pattern is:
- download a pdf in Qutebrowser
- press `Super + f`
- type a few letters from the filename + `Enter`

And then the PDF is opened in Zathura. This works for me, but could definitely be streamlined even more if you integrated it with a keybinding inside Qutebrowser.

**Comment by jcguu95** [comment]
Oh no! I was then so new to github that completely missed the message!
I haven't either written my first script then.. now it is all clear to me, and your workflow is perfect! Thank you.
