### ISSUE TITLE
Suggestion: make regex for pdf-opener case-insensitive

### ISSUE THREAD

**Issue by d-nnis** [jamesbvaughan/dotfiles#2]
Hey there,

in order for all PDF-findings to be formated/ substituted in the same way I suggest to make the sed-string case-insensitive, like so: ``sed -e "s#$HOME/\(.*\)\.pdf#\1#gi" ``

I changed it that way since many PDFs have an upper-case extension.

Anyway, thanks for the idea!

**Comment by jamesbvaughan** [comment]
Thanks for the suggestion, I'll update my script!
